image: hosttoday/ht-docker-dbase:npmts
services:
  - docker:dind

stages:
  - build
  - test
  - release
  - trigger

before_script:
  - npmci prepare docker-gitlab


build:
  stage: build
  script:
    - npm install
    - npm test
    - npmci build docker
  tags:
    - lossless
    - priv
  

test:
  stage: test
  script:
    - npmci test docker
  tags:
    - lossless
    - priv

release:
  image: hosttoday/ht-docker-node:npmts
  stage: release
  script:
    - npmci publish npm
  only:
    - tags
  tags:
    - lossless
    - priv

trigger:
  image: hosttoday/ht-docker-node:npmts
  stage: trigger
  script:
    - npmci trigger
  only:
    - tags
  tags:
    - lossless
    - priv