image: hosttoday/ht-docker-dbase:npmci
services:
  - docker:dind

cache:
  paths:
  - .yarn/
  key: "$CI_BUILD_STAGE"

stages:
  - test
  - release
  - trigger
  - pages

before_script:
  - npmci prepare docker-gitlab

test:
  stage: test
  script:
    - npmci test stable
  tags:
    - lossless
    - priv

release:
  image: hosttoday/ht-docker-node:npmci
  stage: release
  script:
    - npmci publish npm
  only:
    - tags
  tags:
    - lossless
    - priv

trigger:
  image: hosttoday/ht-docker-node:npmci
  stage: trigger
  script:
    - npmci trigger
  only:
    - tags
  tags:
    - lossless
    - priv

pages:
  image: hosttoday/ht-docker-node:npmci
  stage: pages
  script:
    - npmci command yarn global add npmpage
    - npmci command npmpage --publish gitlab
  tags:
    - docker
  only:
    - tags
  artifacts:
    expire_in: 1 week
    paths:
    - public